ersion: "3.7"
services:
  app:
    image: nicbet/phoenix:1.6.15-alpine
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./app:/app
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    # depends_on:
